export const artists = `artist,bio,video,genre,vocal,vibe,energy,facebookLink,instagramLink,twitterLink,songPreviewName,songPreviewStyle,artistThumbnail,artistHeroImage,altImage1,altImage2,altImage3
Robbie Miller,"Having spent the past 12 years intricately developing his vocal prowess, Robbie Miller is now proving to be a promising and exciting new force on the Australian music scene. As an emerging artist, Robbie has already achieved some impressive feats. Hailed as an insightful and “heartfelt” lyricist (The Music), Robbie launched onto the scene in 2013 as Triple J Unearthed’s National Indigenous Music Awards (NIMAs) winner with his song Don’t Go Walking Away. The track gained immediate attention at Triple J, and a result of this and his NIMAs win.",ciZH8IGAIWI,Singer Songwriter,Male,Emotive,Slow,https://www.facebook.com/RobbieMillerMusic/,https://www.instagram.com/robbiemillermusic/,https://twitter.com/robbiemillerrr,Road_RobbieMiller_YoungTribe.mp3,Singer Songwriter,RobbieMiller_TN.jpg,RobbieMiller.jpg,RobbieMillerAlt1.jpg,RobbieMillerAlt2.jpg,RobbieMillerAlt3.jpg
Yoste,"Yoste is the moniker of 23-year-old Brisbane singer-songwriter-producer Kurt Sines. With influences drawn from the likes of Bon Iver, Tycho and Jonsi to LANY and the 1975 the project’s unique and moving music is swiftly gaining international attention.

In 2016, following several months of travel and introspection, the self-taught songwriter and producer dazzled audiences with the release of his debut single ‘Chihiro’.

Now with a catalogue boasting over 30 million streams online, a sold out debut show in late 2017 and a debut EP heralded by standout single 'Arc' due later this year, the young musician looks set to join the ranks of esteemed bedroom producers conquering the world.",e5WYTBhZVIg,Electronic,Male,Chill,Slow,https://www.facebook.com/soundsofyoste/,https://www.instagram.com/soundsofyoste/,,Arc_Yoste_YoungTribe.mp3,Electronic, yoste_TN.jpg, yoste.jpg,YosteAlt1.jpg,YosteAlt2.jpg,YosteAlt3.jpg
Braille Face,"is Melbourne singer songwriter Jordan White.  His music has been covered online by DUMMY, DAZED, Majestic Casual, CLASH, Indie Shuffle, COLORS Berlin, The Line of Best Fit, The 405, The Quietus, Pilerats, Purple Sneakers and more. His combined streams on Spotify & Apple Music recently surpassed 2 million, and his champions on radio include Mary Anne Hobbs, Guy Garvey and Nemone at BBC 6 Music, Travis Holcombe at KCRW, Richard Kingsmill at triple j and Zan Rowe at Double J.",n78tN528ehc,Electronic,Male,Chill,Medium,https://www.facebook.com/braillefaces/,https://www.instagram.com/brailleface/,https://twitter.com/braille_face,From_BrailleFace_YoungTribe.mp3,Electronic,BrailleFace_TN.jpg,BrailleFace.jpg,BrailleFaceAlt1.jpg,BrailleFaceAlt2.jpg,BrailleFaceAlt3.jpg
Eilish Gilligan,"Eilish Gilligan is a producer, singer and songwriter from Melbourne. She hasn’t been releasing music under her own name for long – you might know her better as the magnetic frontperson in Frida, or from touring as a vocalist in Japanese Wallpaper’s band – but in her eighteen months as a solo artist Eilish has achieved an incredible amount. In 2016 alone Eilish received airplay across triple j, Double J and Unearthed, and supported local upstarts Alex Lahey and Confidence Man. Her warm, spectral pop music has earned well-deserved praise from triple j’s Zan Rowe and Dom Alessio, as well as a feature on the Bandcamp homepage.",sjeE1bYiVoY,Pop,Female,Energetic,Medium,https://www.facebook.com/eilishgilliganmusic/,https://www.instagram.com/eilishgilligan/?hl=en,https://twitter.com/eilishgilligan,The Feeling_EilishGilligan_YoungTribe.mp3,Pop,EilishGilligan_TN.jpg,EilishGilligan.jpg,EilishGilliganAlt1.jpg,EilishGilliganAlt2.jpg,EilishGilliganAlt3.jpg
Morning Harvey,"“Seriously, though. You need to be on this now” were the words of John Richards from KEXP Seattle, one of Americas most influential radio stations for new music. KEXP gave the band their stamp of approval in 2015 with the highly sought after placement of ‘Song Of The Day’ with the single ‘Smith Street Swap Meet’, leading to many US College Radio stations championing the band which saw their EP storming the CMJ Radio 200 Charts for 3 weeks.",twvzl-wP1x8,Indie Pop,Male,Energetic,Fast,https://www.facebook.com/morningharveymusic/,,https://twitter.com/morningharvey,Holy Gun_MorningHarvey_YoungTribe.mp3,Indie Pop,MorningHarvey_TN.jpg,MorningHarvey.jpg,MorningHarveyAlt1.jpg,MorningHarveyAlt2.jpg,MorningHarveyAlt3.jpg
Banff,"Ethereal layers of spacious, soul-drenched indie-pop – that is the craft of singer-songwriter BANFF. Benjamin Forbes the former front-man of Brisbane group Little Casino, stepped away from the band environment mid-2014 with a thirst to explore new songwriting ground, something he has achieved in spades with his debut EP ‘Future Self’.",TnfR8IbWpTA,Singer Songwriter,Male,Emotive,Medium,https://www.facebook.com/banffmusic/,https://www.instagram.com/banffmusic/?hl=en,https://twitter.com/banff_music?lang=en,The Great Unknown_Banff_YoungTribe.mp3,Singer Songwriter,banff_press1_img_8310_print_large1_TN.jpg,banff_press1_img_8310_print_large1.jpg,BanffAlt1.jpg,BanffAlt2.jpg,BanffAlt3.jpg
Band Of Frequencies,"True believers in sounds beyond boundaries, Band of Frequencies draw their influences from a vast spectrum of roots, rock, electronic and psychedelic styles. Their signature blend comes from years of live experimentation, constantly pushing their influences into the creative fires to see what melts, what explodes and what merges. They have now successfully forged a bond of sonic elements that represents their coastal roots and strikes a chord in the hearts of passionate music lovers around the globe. It's this quality that has lead to invitations to grace the stages of diverse festivals, at home and abroad, and to record soundtracks to several internationally released surf films.",XveSx4VBIBs,Blues & Roots,Male,Chill,Medium,https://www.facebook.com/bandoffrequencies/,,,Wanderlust_BandOfFrequencies_YoungTribe.mp3,Blues & Roots,BandOf Frequencies_TN.jpg,BandOf Frequencies.jpg,BandOfFrequenciesAlt1.jpg,BandOfFrequenciesAlt2.jpg,BandOfFrequenciesAlt3.jpg
Future Jr,"Future Jr. is the sonic tapestry forged by new Australian artist, Matthew Nainby. Influenced by the likes of Toro y Moi, Lorde and Day Wave, Nainby began his alchemy in the depths of his parents house, with guitar in hand crouched over the glow of his synth collection. Armed with a disarming lyricism and a love for immersive musical textures, he has bound together a collection of intriguing electro-pop offerings.",K6qhxSdX5g4,Indie Pop,Male,Happy,Medium,https://www.facebook.com/futurejr,https://www.instagram.com/futurejr_/,https://twitter.com/futurejr_,Tell Me That I'm Wrong_FutureJr_YoungTribe.mp3,Indie Pop,Future JR_TN.png,Future JR.png,FutureJrAlt1.jpg,FutureJrAlt2.jpg,FutureJrAlt3.jpg
Edward R,"Edward R. is the chamber-pop project from Melbourne musician Geoffrey Roberts. His forthcoming new material showcases intricate, immersive, psychedelic pop thatrecalls Ariel Pink and Unknown Mortal Orchestra, and follows 2016’s EP 'Agrabah', which featured 'Wolves And The Water’, a track streamed over four million times.",tWsGEeAJ5lQ,Singer Songwriter,Male,Emotive,Medium,https://www.facebook.com/Edward.R.Music,,https://twitter.com/edward_r_music,Call Me Home_EdwardR_YoungTribe.mp3,Singer Songwriter,Edward R_TN.jpg,Edward R.jpg,EdwardRAlt1.jpg,EdwardRAlt2.jpg,EdwardRAlt3.jpg`;
